endpoint: Fix race when reading endpoint properties
The endpoint property map is protected by the endpoint mutex. However,
it seems that the internal getter was not always called with the
endpoint mutex held.

This commit fixes that issue by renaming the internal accessors to have
the commonly used "locked" suffix. All call sites in `pkg/endpoint` were
manually inspected if they need to use the protected or unprotected
accessor and changed accordingly.

This fixes a rare cilium-agent crash where Go detected the concurrent
mutation of the endpoint property map (excerpt):

```
fatal error: concurrent map read and map write
goroutine 9221 [running]:
internal/runtime/maps.fatal({0x567336f?, 0xc28adfbec4e68c4b?})
 /usr/local/go/src/runtime/panic.go:1046 +0x18
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).isProperty(...)
 /go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2749
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runPreCompilationSteps(0xc0001c6f08, 0xc006ca7688)
 /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:667 +0x1a5
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc0001c6f08, 0xc006ca7688)
 /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:402 +0x1fc
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc0001c6f08, 0xc006ca7688)
 /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:504 +0x65a
github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc001e08340, 0xc007bc3260)
```

Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>